apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: flagger-manifests
spec:
  interval: 6h
  url: oci://ghcr.io/fluxcd/flagger-manifests
  ref:
    semver: 1.x
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loadtester
spec:
  interval: 30m
  targetNamespace: flagger-system
  path: "./tester/"
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flagger-manifests
  wait: true
