apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - kustomizeconfig.yaml
resources:
  - linkerd-crds.yaml
  - linkerd-control-plane.yaml
  - linkerd-viz.yaml
  - linkerd-smi.yaml
  - linkerd-certs.yaml
  - repositories.yaml
  - namespaces.yaml
secretGenerator:
  - name: linkerd-trust-anchor
    namespace: linkerd
    type: kubernetes.io/tls
    files:
      - tls.crt=ca.crt
      - tls.key=ca.key
